language: scala
scala:
  - 2.10.6
  - 2.11.8

sudo: false

script: sbt ++$TRAVIS_SCALA_VERSION test -Dloglevel=debug

before_install:
  - rvm install 2.1.5
  - rvm use 2.1
  - gem install fluentd

jdk:
 - openjdk7
 - oraclejdk7
 - oraclejdk8

branches:
  only:
    - master
    - develop

notifications:
  email:
    - leo@xerial.org
    - ozawa.tsuyoshi@gmail.com

matrix:
  include:
  - scala: 2.12.1
    jdk: oraclejdk8
